### ISSUE TITLE
Remove Drush mode

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#102]
I personally started using `b` because I needed better multisite support than what Drush has/had. While I do currently have both installed on my server, I intend to remove Drush (or at least the Backdrop part of it, since I still host some Drupal sites) once `b` has a stable release. In terms of why other people might use `b`, I imagine one reason is that they don't like Drush's install process (Composer, Drupal Drush, Backdrop Drush, etc.)...

`b` has a 'drush mode' that can be enabled with the `--drush` option which apparently* lets you run Drush commands through `b`.
(\* I haven't actually tested/used this)

I'm struggling to see a use case for wanting to do this. I'm therefore wondering if we can/should remove all Drush-related code from `b` to streamline it and simplify maintenance...? What do others think?

**Comment by indigoxela** [comment]
I'm using `b`, because - to my opinion - drush didn't seem to be the right tool for Backdrop. It has been made for Drupal and as its development moves on, it will move further away from what's needed for Backdrop.

I use it on a mixed Drupal/Backdrop dev VM and wanted to have something that doesn't interfere with my Drupal sites.

Personally, I've never used that drush-mode, so I'm all for removing it. Is there someone, who's using it anyway?

Simplified maintenance is a good reason, too.

**Comment by ghost** [comment]
@Gormartsen @serundeputy Care to weigh in? Do you guys still use `b` and/or its Drush mode?

**Comment by serundeputy** [comment]
indifferent; haven't used `b` in some time.

**Comment by ghost** [comment]
Let's remove it then.

**Comment by ghost** [comment]
Here's a rough PR (just `grep`ed 'drush' and removed as necessary): https://github.com/backdrop-contrib/b/pull/103

**Comment by indigoxela** [comment]
Yep, https://github.com/backdrop-contrib/b/pull/103 removes (almost) all drush stuff.

The README might need some update, as it still references drushrc.
So does commands/Core/site_install.b.inc (`b help site-install`)

`b` still works fine.

**Comment by ghost** [comment]
Thanks. I'll update the other places as I come across them (doing a fair bit of refactoring for another issue).
