### ISSUE TITLE
Provide a user friendly message if shell_exec function is not available

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#289]
Despite previously enabling it, my host appears to have disabled `shell_exec()` and as the php config was set not to show errors, it was silently failing and once I checked the error log then I discovered what was happening.

Bee should check the presence of this function and gracefully exit with an error message if the command needs this to function.

**Comment by indigoxela** [comment]
One thing came to my mind, when looking at download.bee.inc last time: isn't it possible to do that without shell_exec?
The command uses both, curl and wget, and both shell_exec and exec.

There might be a way to avoid that. :thinking: Requires a lot of rewrite, though...

**Comment by yorkshire-pudding** [comment]
Definitely worth further investigation.

**Comment by indigoxela** [comment]
Here's a suggestion to replace all exec() or shell_exec() in the download command with php curl handles.

@yorkshire-pudding  As it's required to use a UserAgent string (GitHub refuses to play otherwise), the question is, what this string should be. Currently I use "Bee" as placeholder, but maybe we should use a constant, and maybe we should make it more verbose... What do you think?

The change is quite big and requires thorough testing. What a pity I'm not able to fix the workflow. :cry: I'm not using Lando and can't run the tests locally, but I think, you can.

To test the changes, you need to find a contrib project, that doesn't have a release, yet.

**Comment by indigoxela** [comment]
Addendum: I completely removed all handling for wget progressbar, and added a deprecation notice to the help text.

There's no actual equivalent in curl_setopt, CURLOPT_NOPROGRESS set to false is awfully ugly, and a custom progressbar callback seemed overdone to me. Actually for me the progress bar is rather a bug, than a feature, but ... your mileage may vary. :wink:

**Comment by yorkshire-pudding** [comment]
> @yorkshire-pudding As it's required to use a UserAgent string (GitHub refuses to play otherwise), the question is, what this string should be. Currently I use "Bee" as placeholder, but maybe we should use a constant, and maybe we should make it more verbose... What do you think?

@indigoxela - I think we should use 'Bee - the command line tool for Backdrop CMS' - reason in the PR review.  I agree with making it a constant, I counted four instances.  Were you thinking of a global constant or just within the download command file? I'm fine either way.

I've ran the tests as it was and with the longer USER AGENT string and they all pass.
We should clean up the tests using `--hide-progress`; I've referred to the files in the PR review.

> To test the changes, you need to find a contrib project, that doesn't have a release, yet.
I tested with `entityform` and it works.

Thank you very much for this fix.

**Comment by yorkshire-pudding** [comment]
Thank you @indigoxela - a great solution to this issue.
