### ISSUE TITLE
Incorrect 'Bee has detected that it is installed within the Backdrop root' message

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/b#336]
Following instructions on the README I tried to create a symlink only to get:

```bash
alan@new-web:/usr/local/src/bee$ sudo -s /usr/local/src/bee/bee.php /usr/local/bin/bee

 [!] Bee has detected that it is installed within the Backdrop root. This is not recommended. It is recommended to install Bee in your home directory (e.g. '~/bee/). 
 [✘] There is no '/usr/local/bin/bee' command.                                                                                                                        

alan@new-web:/usr/local/src/bee$
```
Bee is not inside of Backdrop root.

**Comment by yorkshire-pudding** [comment]
@alanmels
Firstly, the command looks wrong - for a link there should be `ln -s ...`
Secondly, because your session is within the folder where you've installed `bee` if you did run a command there, and didn't use the `--root=/path/to/backdrop/root` option then bee would look at the current directory. Without Backdrop there many commands would fail but you could still download core.

**Comment by alanmels** [comment]
Thanks for the update. I made a typo, of course, the command is `ln -s`, however even with the correct command it gives the same error. But I see why it does so from your second argument. Fair enough, but the wording "within the Backdrop root" is misleading here. Would be clearer if it was something like "within the bee installation folder".

**Comment by yorkshire-pudding** [comment]
@alanmels - the reason for this approach is because during the Bee session in the last Backdrop Live, an attendee asked what would happen if bee was installed within the backdrop root. In #334 I added a warning if bee detects that the directory of the `bee.php` script contains the backdrop root.

I can't think of any reason why someone would run bee from the bee installation folder (except by accident).  Even if you did, then bee is right to assume that you're planning to install backdrop there.  Incidentally, in the bee testing environment, we create two subfolders within the bee folder for the testing sites, but because they are in a sub folder they will not trigger this warning as the bee location does not contain the full backdrop root.

**Comment by yorkshire-pudding** [comment]
@alanmels I have added a check so the message is less misleading in #339
